# Generated by Django 4.2.21 on 2025-07-05 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_model_87dc6f',
            fields=[
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
