# Generated by Django 4.2.21 on 2025-07-05 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_user_model_371dfd'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_model_0b19a1',
            fields=[
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
