# Generated by Django 4.2.21 on 2025-07-05 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_user_model_a98ee3'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_model_818fe0',
            fields=[
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
