# Generated by Django 4.2.21 on 2025-07-05 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_user_model_818fe0'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_model_60ea13',
            fields=[
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='user_model_fb8733',
            fields=[
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
