# Generated by Django 4.2.21 on 2025-07-05 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_user_model_60ea13_user_model_fb8733'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_model_5ed113',
            fields=[
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
