# Generated by Django 4.2.21 on 2025-06-30 11:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_userprofile_schemas_alter_userprofile_database'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='database',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
