# Generated by Django 4.2.21 on 2025-06-30 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_userprofile_profile_id_alter_userprofile_database'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='database',
            field=models.JSONField(default=dict),
        ),
    ]
