# Generated by Django 4.2.21 on 2025-07-03 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_userproject_delete_testmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userproject',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userproject', to='main.userprofile'),
        ),
    ]
