# Generated by Django 4.2.21 on 2025-07-04 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_userproject_user_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='database',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='schemas',
        ),
    ]
