# Generated by Django 4.2.21 on 2025-07-04 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_userprofile_database_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userproject',
            name='name',
            field=models.TextField(),
        ),
    ]
